### ISSUE TITLE
Github Repo

### ISSUE THREAD

**Issue by wpexplorer** [makeitworkpress/wp-updater#1]
Hey,

Any chance you would consider adding this to the WP Repository as a plugin? This way other theme's and plugins could recommend your plugin as the updater for their products.

I know I could do it myself, but I don't like taking other people's hard work and claiming it as my own.

- AJ

**Comment by leichim** [comment]
He AJ, there are already a couple of other plugins doing the same I believe. The purpose of this script is that it can be included in other plugins. 

Since the code is open-source, feel free to use it in a plugin of yours. No problem taking this hard work further!

Michiel
